type Factory @entity {
  # factory address
  id: ID!
  # deployer address
  deployer: ID!
  # uni v3 factory address
  uniV3Factory: ID!
  # observation cardinality min
  minCardinality: BigInt!
  # amount of pools created
  poolCount: BigInt!
  # amount of all time transactions
  txCount: BigInt!
  # factory owner
  owner: ID!
  # pools deployed by factory
  pools: [Pool!]! @derivedFrom(field: "factory")
}

type Pool @entity {
  # pool address
  id: ID!
  # pool tokens name
  tokenPair: String!
  # pool address in Bytes
  address: Bytes!
  # decimals for pool token
  decimals: BigInt!
  # factory address
  factory: Factory!
  # oracle address:
  oracle: ID!
  # created timestamp
  createdAtTimestamp: BigInt!
  # created block number
  createdAtBlockNumber: BigInt!
  # token0
  token0: Token!
  # token1
  token1: Token!
  # maintenance margin
  maintenance: BigInt!
  # all time number of transactions
  txCount: BigInt!
  # fee
  fee: BigInt!
  # reward
  rewardPremium: BigInt!
  # liquidity locked
  liquidityLocked: BigInt!
  # positions held on pool
  positions: [Position!]! @derivedFrom(field: "pool")
  # staking rewards pool
  stakePool: StakePool
  # reward tokens
  rewardTokens: [ID!]!
}

type MultiRewardsFactory @entity {
  # multirewards factory address
  id: ID!
  # stake pools deployed by multirewards factory
  stakePools: [StakePool!]! @derivedFrom(field: "multiRewardsFactory")
}

type StakePool @entity {
  # multirewards address
  id: ID!
  # multirewards factory
  multiRewardsFactory: MultiRewardsFactory!
  # pool for multiwards (optional)
  pool: Pool
}


type Token @entity {
  # token address
  id: ID!
  address: ID!
  # token symbol
  symbol: String!
  # token name
  name: String!
  # token decimals
  decimals: BigInt!
  # chain ID where the token exists
  chainId: Int!
}

type TokenPositionMapping @entity {
  id: ID!
  tokenId: String!
  positionId: String!
  poolAddress: ID!
}

type Position @entity {
  # poolAddress-positionId 
  id: ID!
  # tokenId 
  tokenId: String
  # positionId in pool
  positionId: String!
  # owner of position
  owner: ID!
  # pool address of position
  pool: Pool!
  # initial margin at time of open
  initialMargin: BigInt
  # initial sqrtPriceX96After at time of open
  initialSqrtPriceX96After: BigInt
  # margin
  margin: BigInt
  # margin amountOut at time of close / liquidate
  marginAmountOut: BigInt
  # position zeroForOne
  zeroForOne: Boolean
  # created at block number
  blockNumber: BigInt
  # created at timestamp
  timestamp: BigInt
  # created at tx hash
  transaction: Transaction!
  # is position liquidated
  isLiquidated: Boolean!
  # is position settled
  isSettled: Boolean!
  # either settled/liquidated is true
  isClosed: Boolean!
  # escrow rewards 
  rewards: BigInt
  # position transactions
  transactions: [Transaction!]! @derivedFrom(field: "position")
}

type Transaction @entity {
  # tx hash
  id: ID!
  # tx type
  type: String
  # block txn was included in
  blockNumber: BigInt!
  # tx sender
  sender: ID!
  # timestamp txn was confirmed
  timestamp: BigInt!
  # gas settings during tx execution
  gasLimit: BigInt!
  gasPrice: BigInt!
  # Related position (if this transaction is for a position)
  position: Position
}

type Mint @entity {
  # transaction hash
  id: ID!
  # NFT token ID
  tokenId: BigInt!
  # sender address
  sender: Bytes!
  # recipient address
  recipient: Bytes!
  # position ID in pool
  positionId: BigInt!
  # position size
  size: BigInt!
  # position debt
  debt: BigInt!
  # margin amount
  margin: BigInt!
  # fees paid
  fees: BigInt!
  # rewards earned
  rewards: BigInt!
  # related transaction
  transaction: Transaction!
  # related position
  position: Position!
}

type Ignite @entity {
  # transaction hash
  id: ID!
  # NFT token ID
  tokenId: BigInt!
  # sender address
  sender: Bytes!
  # recipient address
  recipient: Bytes!
  # amount out
  amountOut: BigInt!
  # rewards earned
  rewards: BigInt!
  # related transaction
  transaction: Transaction!
  # related position
  position: Position!
}

type Lock @entity {
  # transaction hash
  id: ID!
  # NFT token ID
  tokenId: BigInt!
  # sender address
  sender: Bytes!
  # margin after lock
  marginAfter: BigInt!
  # related transaction
  transaction: Transaction!
  # related position
  position: Position!
}

type Free @entity {
  # transaction hash
  id: ID!
  # NFT token ID
  tokenId: BigInt!
  # sender address
  sender: Bytes!
  # margin after free
  marginAfter: BigInt!
  # related transaction
  transaction: Transaction!
  # related position
  position: Position!
}
